add basic building script for travis

diff --git a/ops/travis/build/test-images b/ops/travis/build/test-images
--- a/ops/travis/build/test-images
+++ b/ops/travis/build/test-images
@@ -3,3 +3,43 @@
 set -euo pipefail
 IFS=$'\n\t'
 
+export DOCKER_IMAGE_TAG=$(exec ops/travis/helpers/build_docker_image_tag)
+
+before_install() {
+    bash ops/travis/helpers/install_docker_compose;
+    bash ops/travis/helpers/show_system_versions;
+    env
+}
+
+install() {
+    echo "nothing to install..."
+}
+
+before_script() {
+    # pull some cache?
+}
+
+script() {
+    make build
+}
+
+after_success() {
+    echo "build succeeded"
+}
+
+after_failure() {
+    echo "build failed"
+    env
+    docker images
+}
+
+# Check if the function exists (bash specific)
+if declare -f "$1" > /dev/null
+then
+  # call arguments verbatim
+  "$@"
+else
+  # Show a helpful error
+  echo "'$1' is not a known function name" >&2
+  exit 1
+fi
